name: nxt_test_case
description: "test case for nxt"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <3.3.0'
  flutter: ">=3.16.0 <3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #UI
  cupertino_icons: 1.0.8
  material_design_icons_flutter: 7.0.7296
  sizer: 2.0.15
  auto_size_text: 3.0.0
  flutter_spinkit: 5.2.1
  google_fonts: 6.2.0
  cached_network_image: 3.3.1
  flutter_rating_bar: 4.0.1
  flutter_widget_from_html: 0.14.11
  flutter_svg: 2.0.10+1
  modal_bottom_sheet: 3.0.0
  #Core
  flutter_hooks: 0.20.5
  stacked: 3.4.2
  stacked_services: 1.5.0
  observable_ish: 4.0.8
  auto_route: 8.1.0
  get_it: 7.6.7
  rxdart: 0.27.7
  #NETWORK
  dio: 5.4.3+1
  built_value: 8.9.2
  dio_http_cache: 0.3.0
  dio_cache_interceptor: 3.5.0
  pretty_dio_logger: 1.3.1
  connectivity_plus: 6.0.2
  #Utils
  shared_preferences: 2.2.3
  open_file: 3.3.2
  intl: 0.18.1
  equatable: 2.0.5
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  dartz: 0.10.1
  fpdart: 1.1.0
  logger: 2.2.0
  geocoding: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  build_runner: 2.4.9
  built_value_generator: 8.9.2
  json_serializable: 6.7.1
  freezed: 2.5.2

dependency_overrides:
  dio: 5.4.3+1
  json_serializable: 6.7.1
  freezed: 2.5.2
  modal_bottom_sheet:
    git:
      url: https://github.com/mahmourad98/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/vectors/
    - assets/images/bitmaps/