name: nxt_test_case
description: "test case for nxt"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <3.3.0'
  flutter: ">=3.16.0 <3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8
  material_design_icons_flutter: 7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3


flutter:
  uses-material-design: true